[package]
name = "secret-rare/rbx-reface"
version = "1.0.0"
description = "Restore classic decal faces following the Dynamic Head Migration."
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
